### ISSUE TITLE
Get build flow cleaned up

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ExtensionLayer#32]
In order to improve adding more layers in the future and making sure everything works on major platforms (Windows, Linux, Android, etc) there are a few things that could be fixed

- [x] [script](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/update_deps.py) with [known good file](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/known_good.json) to grab things like Vulkan Headers (same as Validation Layers and glslang use)
- [ ] Directory structure for common files and for each layer
- [ ] CMake flag to build only single layer
- [ ] Make sure it builds on 
  - [ ] Windows
  - [x] Linux
  - [ ] Android
- [ ] Way to test against CTS (can be done in CI)
  - [ ] Run with Validation Layers behind to make sure valid Vulkan is being produced if calls are made
- [x] README directions to build (point else where how to use)
- [ ] Version for each layer per change (to be queried in `VkLayerProperties::implementationVersion`
- [ ] Release binaries hosted on GitHub ( like how [Validation Layers release for Android](https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/sdk-1.2.141.0) ) 

Bonus:
- [ ] clang-format check in CI (would just use the same [config](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/.clang-format) as validation layers)
- [ ] Markdown write up with some information about background of each layer added

**Comment by Tobski** [comment]
> CMake flag to build only single layer

For this, I'd kind of expect there to be a single layer; otherwise we're just introducing a bunch of overhead by indirecting through all the layers. The same conclusion was reached by the (now singular) validation layer. Build flags to exclude extensions from the build wouldn't be a terrible idea though.

We should probably come up with a set of guidelines on how to contribute extensions (e.g. conventions they should use like how to adhere to build flags), and how to ship this layer with an application.

We should also add an implementation of [VK_EXT_private_data ](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_private_data.html) as a part of the baseline changes as well, since it's almost guaranteed we'll need that for future extensions, otherwise this wheel will simply be reinvented over and over again (maybe that should be a separate issue?).

**Comment by djdeath** [comment]
There are CI Linux/MacOS builds. It's based off what the validation layers have.

**Comment by sfricke-samsung** [comment]
The difference is the old Validation Layers made no sense by themselves. For this, I wouldn't want to force the overhead of one extension layer over the other

As fo VK_EXT_private_data, there will be implementations that don't support it and that needs to be accounted for

**Comment by sfricke-samsung** [comment]
So basically everything I wanted out of this issue was added with the sync2 layer
